# Generated by Django 3.1.6 on 2021-02-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.TextField(max_length=50)),
                ('Event_Name', models.TextField(max_length=50)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
    ]
