# Generated by Django 3.1.6 on 2021-02-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/')),
                ('Event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_data.participantdata')),
            ],
        ),
    ]
