# Generated by Django 3.1.6 on 2021-02-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0002_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Event_name',
            new_name='Event_Name',
        ),
    ]
