# Generated by Django 3.1.6 on 2021-02-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0005_auto_20210216_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantdata',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
